# Use an official lightweight Node.js image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# This command will be run when the container starts
# It will execute a file named 'index.js' with Node.js
CMD ["node", "index.js"]